services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: faroc
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - store

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - store

  eureka-server:
    container_name: eureka-server
    image: fajr0cha/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - store
    depends_on:
      - zipkin

  api-gateway:
    container_name: api-gateway
    image: fajr0cha/api-gateway:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - store
    depends_on:
      - zipkin
      - eureka-server

  customer:
    container_name: customer
    image: fajr0cha/customer:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - store
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - api-gateway
      - rabbitmq

  fraud:
    container_name: fraud
    image: fajr0cha/fraud:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - store
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - api-gateway

  notification:
    container_name: notification
    image: fajr0cha/notification:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - store
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - api-gateway
      - rabbitmq

networks:
  postgres:
    driver: bridge
  store:
    driver: bridge

volumes:
  postgres:
  pgadmin: