spring:
  application:
    name: eureka-server
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %clr(%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]) %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){magenta} : %m%n%wex"
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans